# -*- coding: utf-8 -*-
"""proiect_AD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11NjOjVm--2gFA9v5JKku9k_qhMPUQH3v
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA


# Set the aesthetic style of the plots
sns.set_style('whitegrid')

got = pd.read_csv('/content/drive/MyDrive/DataSets/character-deaths.csv')
got

got.shape

got.info()

got.describe(include='all')

got.isnull().sum()

#   --- Data preprocessing ---
# Removing duplicates
got_prep=got.drop_duplicates()
got_prep

#add 0 to "death year" where values are missing (characters are still alive)

got_prep['Death Year']=got_prep['Death Year'].fillna(0)
got_prep['Death Year']=got_prep['Death Year'].astype('int')
#got_prep
#schimb tipul de data col 'gender' in boolean
got_prep['Gender']=got_prep['Gender'].astype('bool')
#schimb tipul de data col 'Nobility' in boolean
got_prep['Nobility']=got_prep['Nobility'].astype('bool')
got_prep.info()
got_prep

#add 'unknown' to the 'Allegiances' column where the values are missing
got_prep['Allegiances']=got_prep['Allegiances'].fillna('unknown')
got_prep.isnull().sum()

# for 'book of death' and 'death chapter' assign a different value to indicate that the characters are still alive
got_prep['Book of Death']=got_prep['Book of Death'].fillna('-1')
got_prep['Death Chapter']=got_prep['Death Chapter'].fillna('-1')
got_prep['Book Intro Chapter']=got_prep['Book Intro Chapter'].fillna('1')
#make them int
got_prep['Book of Death']=got_prep['Book of Death'].astype('int')
got_prep['Death Chapter']=got_prep['Death Chapter'].astype('int')
got_prep['Book Intro Chapter']=got_prep['Book Intro Chapter'].astype('int')
got_prep.info()
got_prep.isnull().sum()

''' How does the number of deaths compare between commoners and nobility in Game of Thrones? '''

death_nobility = got_prep[got_prep['Death Year'] > 0]['Nobility'].value_counts()
plt.figure(figsize=(4, 2))
sns.barplot(x=death_nobility.index, y=death_nobility.values)
plt.title('Number of Deaths by Nobility')
plt.xlabel('Status')
plt.ylabel('Number of Deaths')
plt.xticks([0, 1], ['Commoner', 'Nobility'])
plt.show()

''' How does the number of deaths compare between male and female characters in Game of Thrones? '''

death_gender = got_prep[got_prep['Death Year'] > 0]['Gender'].value_counts()
plt.figure(figsize = (4, 2))
sns.barplot(x = death_gender.index, y = death_gender.values)
plt.title('Number of Deaths by Gender')
plt.xlabel('Gender')
plt.ylabel('Number of Deaths')
plt.xticks([0, 1], ['Male', 'Female'])
plt.show()

''' How many characters belong to each allegiance in Game of Thrones? '''
# Count the number of characters for each allegiance
allegiances_count = got_prep['Allegiances'].value_counts()

# barplot
plt.figure(figsize=(6, 3))
sns.barplot(x=allegiances_count.index, y=allegiances_count.values)
plt.title('Distribution of Characters by Allegiances')
plt.xlabel('Allegiances')
plt.ylabel('Number of Characters')
plt.xticks(rotation=90)  # Rotate x-axis labels for better readability
plt.show()

''' How are character deaths distributed across book chapters in Game of Thrones? '''
# Filter out only valid values (exclude -1)
filtered_data = got_prep[got_prep['Death Chapter'] != -1]

# Create histogram
plt.figure(figsize=(6, 3))
sns.histplot(filtered_data['Death Chapter'], bins=40, kde=False, color='blue')
plt.title("Distribution of Death Chapters")
plt.xlabel("Death Chapter")
plt.ylabel("Frequency")
plt.show()

'''What is the distribution of deaths by allegiance and gender in Game of Thrones?'''
# Group the data by Allegiences and gender
gender_alliance_deaths = got_prep.groupby(['Allegiances', 'Gender']).size().unstack()

# stacked bar chart
plt.figure(figsize=(12, 6))
gender_alliance_deaths.plot(kind='bar', stacked=True, color=['lightblue', 'lightpink'])
plt.title("Deaths by Allegiance and Gender")
plt.xlabel("Allegiance")
plt.ylabel("Number of Deaths")
plt.xticks(rotation=45)
plt.legend(title="Sex")
plt.show()

plt.figure(figsize=(8, 4))
sns.heatmap(got_prep[['Death Chapter','Death Year']].corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

#statistical analysis
#CHI-SQUARE test
'''
H0: Gender has no effect on Nobility.
H1: Gender has an effect on Nobility.
'''
from scipy.stats import chi2_contingency
# Define a function to perform Chi-square test
def chi_square_test(feature1, feature2, alpha=0.05):
    contingency_table = pd.crosstab(got_prep[feature1], got_prep[feature2])
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    #return chi2, p
    print(f"{feature1} vs {feature2}:")
    print(f"Chi-square statistic: {chi2}")
    print(f"P-value: {p}")
    print(f"Degrees of freedom: {dof}")
    print(f"Expected frequencies:\n{expected}")

    # Interpret results
    if p < alpha:
        print("\nConclusion: Reject H0. There is an effect between gender and nobility.")
    else:
        print("\nConclusion: Fail to reject H0. There is no significant effect between gender and nobility.")

# Gender vs Nobility
chi_square_test('Gender', 'Nobility')
#print(f"Gender vs Nobility: Chi-square statistic: {chi2}, P-value: {p}")

import scipy.stats as stats
#ANOVA
'''
H0: There are no significant differences in Book Intro Chapter across different Allegiances.
H1: There are significant differences in Book Intro Chapter across different Allegiances.
'''
#clean the dataset
filtered_data = got_prep.dropna(subset=['Book Intro Chapter', 'Allegiances'])

# group by allegiances
grouped_data = [filtered_data[filtered_data['Allegiances'] == allegiance]['Book Intro Chapter']
                for allegiance in filtered_data['Allegiances'].unique()]

# Perform one-way ANOVA
f_stat, p_value = stats.f_oneway(*grouped_data)

# Display results
print("ANOVA Results:")
print(f"F-Statistic: {f_stat}")
print(f"P-Value: {p_value}")

# Interpret results
if p_value < 0.05:
    print("\nConclusion: Reject H₀. There are significant differences in Book Intro Chapter across different Allegiances.")
else:
    print("\nConclusion: Fail to reject H₀. There are no significant differences in Book Intro Chapter across different Allegiances.")

#PEARSON'S R TEST
'''
H0: There is no significant correlation between Book of Death and Gender.
H1: There is a significant correlation between Book of Death and Gender.

'''
# Clean dataset for analysis
filtered_data = got_prep.dropna(subset=['Book of Death', 'Gender'])

# Split data
book_of_death = filtered_data['Book of Death']
gender = filtered_data['Gender']

# Pearson's R
r, p_value = stats.pearsonr(book_of_death, gender)

# Display results
print("Pearson’s R Test:")
print(f"Correlation Coefficient (R): {r}")
print(f"P-Value: {p_value}")

# Interpret results
if p_value < 0.05:
    print("\nConclusion: Reject H0. There is a significant correlation between Book of Death and Gender.")
else:
    print("\nConclusion: Fail to reject H0. No significant correlation between Book of Death and Gender.")